### ISSUE TITLE
关于 module.exports

### ISSUE THREAD

**Issue by Selina0824** [aliyun/nodejs-acm-sdk#1]
不好意思，index.js中的这个 module.exports = ACMClient;可以改为module.exports.ACMClient = ACMClient;吗？和原先acm-client的结构一致.

**Comment by hyj1991** [comment]
@Selina0824 可以的

**Comment by JacksonTian** [comment]
我感觉没有必要。这个本身就是新的模块。

**Comment by Selina0824** [comment]
@JacksonTian ，本身提这个comments不是因为要兼容acm-client哈，而是我看到[@alicloud/pop-core](https://github.com/aliyun/openapi-core-nodejs-sdk/blob/master/index.js)中的module.exports也是和acm-client类似的写法。eg：
`'use strict';

module.exports = require('./lib/core');
module.exports.ROAClient = require('./lib/roa');
module.exports.RPCClient = require('./lib/core');`

而我们在项目中关于Unit Test的实现是基于sinon封装了一个自己的SDK-Mock的lib， 因此期望各个 SDK的结构是相对一致的。

**Comment by JacksonTian** [comment]
pop-core 中是为了兼容旧的版本而这样加的。

这个模块本身就是新的。
