### ISSUE TITLE
batchGetConfig函数请求头编码的问题

### ISSUE THREAD

**Issue by ke4nec** [aliyun/nodejs-acm-sdk#4]
请求头是GBK时，配置中存在中文会返回异常结果，改成utf-8正常。
`  
 $request.headers = {
          host: this.__get_host(),
          timestamp: this.__get_timestamp(),
          'content-type': 'application/x-www-form-urlencoded;charset=GBK',
          exconfiginfo: 'true',
};     
`

**Comment by hyj1991** [comment]
稍等，确认下

**Comment by ke4nec** [comment]
搞错接口了，貌似是服务器返回的都是iso-8859-1，是中文的话都直接返回3f了

**Comment by hyj1991** [comment]
@ke4nec 经过确认，`batchGetConfig` 这个接口已经废弃了，稍后会更新 SDK 版本去除对应的接口，如果你想要获取多个配置，可以并发调用 `getConfig` 接口
