### ISSUE TITLE
通过批量获取配置接口获取配置信息时，中文字符为乱码

### ISSUE THREAD

**Issue by wang-wen-kun** [aliyun/nodejs-acm-sdk#5]
在响应批量获取配置（batchGetConfig）的请求时，响应体内容采用的编码格式为latin1（response.headers.content-type.charset=ISO-8859-1），导致中文解析有误。

**Comment by hyj1991** [comment]
稍等，确认下

**Comment by hyj1991** [comment]
@ke4nec 经过确认，`batchGetConfig` 这个接口已经废弃了，稍后会更新 SDK 版本去除对应的接口，如果你想要获取多个配置，可以并发调用 `getConfig` 接口

**Comment by wang-wen-kun** [comment]
@hyj1991  好的，谢谢。
